### ISSUE TITLE
Add a gray version of the menubar icon

### ISSUE THREAD

**Issue by juanfcocontreras** [uetchy/juno#2]
Juno is the only color icon in my menubar (most apps use gray menubar icons). Could you add a gray version?

**Comment by uetchy** [comment]
That's great idea! I'm on it.

**Comment by juanfcocontreras** [comment]
Great! Thanks!

**Comment by uetchy** [comment]
Sorry for long waiting 😭 
I've released [v0.3.1](https://github.com/uetchy/juno/releases/tag/v0.3.1) which supports gray icon.

**Comment by juanfcocontreras** [comment]
Thank you! You can close this ticket.
